export const NameShortForms: any = {
  "General Ledger Setup": "GLSetup",
  "Sales & Receivables Setup": "SalesSetup",
  "Purchases & Payables Setup": "PurchSetup",
  "Salesperson/Purchaser": "Salesperson",
};

export const WordShortForms: any = {
  account: "Acc",
  amount: "Amt",
  application: "Appln",
  assembly: "Asm",
  assignment: "Assgnt",
  calculation: "Calc",
  capacity: "Cap",
  component: "Comp",
  credit: "Cr",
  customer: "Cust",
  depreciation: "Depr",
  dimension: "Dim",
  discount: "Disc",
  employee: "Emp",
  exchange: "Exch",
  external: "Ext",
  general: "Gen",
  information: "Info",
  inventory: "Invt",
  invoice: "Inv",
  journal: "Jnl",
  ledger: "Ledg",
  management: "Mgt",
  manufacturing: "Mfg",
  payment: "Pmt",
  production: "Prod",
  purchase: "Purch",
  quantity: "Qty",
  receipt: "Rcpt",
  reconciliation: "Recon",
  register: "Reg",
  reservation: "Reserv",
  resource: "Res",
  routing: "Rtng",
  service: "Serv",
  shipment: "Shpt",
  statement: "Stmt",
  tolerance: "Tol",
  value: "Val",
  vendor: "Vend",
  warehouse: "Whse",
};
